//
//  Declarations.swift
//  mockup2
//
//  Created by Jason Quick on 7/29/23.
//

import Foundation
import SpriteKit

let actionsForDarkPurple = ActionsForDarkPurple()
let actionsForDarkOrange = ActionsForDarkOrange()
let actionsForLightPurple = ActionsForLightPurple()
let actionsForLightOrange = ActionsForLightOrange()
let labels = Labels()
let menuForWhiteSquare1 = MenuForWhiteSquare1()
let menuForWhiteSquare2 = MenuForWhiteSquare2()
let menuForWhiteSquare3 = MenuForWhiteSquare3()
let menuForWhiteSquare4 = MenuForWhiteSquare4()
let menuForWhiteSquare5 = MenuForWhiteSquare5()
let menuForWhiteSquare6 = MenuForWhiteSquare6()
let menuForLightPurpleSquare = MenuForLightPurpleSquare()
let logicForLightPurpleSquares = LogicForLightPurpleSquares()
let menuForDarkPurpleSquare = MenuForDarkPurpleSquare()
let logicForDarkPurpleSquares = LogicForDarkPurpleSquares()
let menuForDarkOrangeSquare = MenuForDarkOrangeSquare()
let logicForDarkOrangeSquares = LogicForDarkOrangeSquares()
let menuForLightOrangeSquare = MenuForLightOrangeSquare()
let logicForLightOrangeSquares = LogicForLightOrangeSquares()
let whiteSquares = WhiteSquares()
let gesture = Gesture()
let longGesture = LongPressGesture()
let squaresImage = SquaresImage()
let logicForWhiteSquares = LogicForWhiteSquares()
let menu2ForWhiteSquare1 = Menu2ForWhiteSquare1()
let menu2ForWhiteSquare2 = Menu2ForWhiteSquare2()
let menu2ForWhiteSquare3 = Menu2ForWhiteSquare3()
let menu2ForWhiteSquare4 = Menu2ForWhiteSquare4()
let menu2ForWhiteSquare5 = Menu2ForWhiteSquare5()
let menu2ForWhiteSquare6 = Menu2ForWhiteSquare6()
let dots = Dots()
let units = Units()
let orangeUnits = OrangeUnits()
let orangeUnits2 = OrangeUnits2()
let enemyUnits = EnemyUnits()
let enemyUnits2 = EnemyUnits2()
let enemySquares = EnemySquare()
let menuForCharacter1Ability = MenuForCharacter1Ability()
let menuForCharacter2Ability = MenuForCharacter2Ability()
let menuForCharacter3Ability = MenuForCharacter3Ability()
let menuForCharacter4Ability = MenuForCharacter4Ability()
let menuForCharacter5Ability = MenuForCharacter5Ability()
let menuForCharacter6Ability = MenuForCharacter6Ability()
let menuForCharacter7Ability = MenuForCharacter7Ability()
let menuForCharacter8Ability = MenuForCharacter8Ability()
let menuForCharacter9Ability = MenuForCharacter9Ability()
let menuForCharacter10Ability = MenuForCharacter10Ability()
let menuForCharacter11Ability = MenuForCharacter11Ability()
let logicForCharacters = LogicForCharacter()
let island = Island()
let characterSelection = CharacterSelection()
let characterDetails = CharacterDetails()
let treasure = Treasure()
